[package]
name = "cfi_asm_mod"
version = "0.2.0"
edition = "2021"
authors = [ "Jonas Jelonek <jonas.jelonek@protonmail.com>" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"shellexpand" = "2.1"